source 'https://rubygems.org'

gem 'activesupport', '5.2.0'
gem 'acts_as_list'
gem 'aws-sdk-rails'
gem 'aws-sdk-rds', '~> 1'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-ses', '~> 1'
gem 'bcrypt', '3.1.7'
gem 'bootstrap', '~> 4.1.3'
gem 'carrierwave'
gem 'carrierwave-base64'
gem 'chunky_png'
gem 'coffee-rails', '4.2.2'
gem 'date_validator'
gem 'dotenv-rails'
gem 'faker'
gem 'fog-aws'
gem 'iso_country_codes'
gem 'jbuilder', '2.7.0'
gem 'jquery-rails', '4.3.3'
gem 'mini_magick'
gem 'mini_racer'
gem 'passenger', '5.2.3'
gem 'pg'
gem 'phonelib'
gem 'puma', '3.7'
gem 'rails', '5.2.0'
gem 'sass-rails', '5.0.7'
gem 'turbolinks', '5'
gem 'uglifier', '4.1.10'

group :development, :test do
  gem 'listen'
  gem 'pry-rails'
  gem 'rspec-rails', '3.7.2'
end
